on:
  push:
    branches: [ testing ]
name: Testing
jobs:
  phpcs:
    name: Check code
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Check Code Standard
      run:
        composer install
        composer lint
