name: testing PHP CI

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  phpcs:
    name: Check code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get latest code
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Check PHP version
      run: php -v
    - name: Check Code Standard
      run: 
        composer install
        composer lint
